# NOTE: Regenerate install.sh if this changes
before:
  hooks:
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/brinfo-scrape
  binary: brinfo-scrape
  goarch:
    - amd64
snapshot:
  name_template: "{{ .Tag }}-next"
