before:
  hooks:
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/brinfo-scrape
  binary: brinfo-scrape
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  # TODO: Enable this
  skip: false
