name: Pull requests

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and test
      run: make build test
    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --snapshot --rm-dist

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
