name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - uses: actions/checkout@v2
    - name: Build and test
      run: make build test
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
    - uses: goreleaser/goreleaser-action@v2
      with:
        args: release --rm-dist
